# Generated by Django 5.2.1 on 2025-05-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="created_at",
            field=models.DateField(verbose_name="Дата создания записи"),
        ),
    ]
