# Generated by Django 5.2.1 on 2025-05-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0002_alter_cashflow_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent_type",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="cash_flow.type",
                verbose_name="Тип",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_flows",
                to="cash_flow.status",
                verbose_name="Статус",
            ),
        ),
    ]
