# Generated by Django 5.2.1 on 2025-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0003_category_parent_type_alter_cashflow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="created_at",
            field=models.DateField(blank=True, verbose_name="Дата создания записи"),
        ),
    ]
